;;; detached-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from detached.el

(autoload 'detached-shell-command "detached" "\
Execute COMMAND with `detached'.

Optionally SUPPRESS-OUTPUT if prefix-argument is provided.

(fn COMMAND &optional SUPPRESS-OUTPUT)" t)
(autoload 'detached-open-session "detached" "\
Open a `detached' SESSION.

(fn SESSION)" t)
(autoload 'detached-compile-session "detached" "\
Compile SESSION.

The session is compiled by opening its output and enabling
`compilation-minor-mode'.

(fn SESSION)" t)
(autoload 'detached-edit-session-annotation "detached" "\
Edit SESSION's annotation.

(fn SESSION)" t)
(autoload 'detached-edit-and-run-session "detached" "\
Edit and re-run SESSION at point.

Optionally TOGGLE-SESSION-MODE.

(fn SESSION &optional TOGGLE-SESSION-MODE)" t)
(autoload 'detached-rerun-session "detached" "\
Re-run SESSION at point.

Optionally TOGGLE-SESSION-MODE.

(fn SESSION &optional TOGGLE-SESSION-MODE)" t)
(autoload 'detached-describe-session "detached" "\
Describe current session." t)
(autoload 'detached-describe-duration "detached" "\
Describe the SESSION's duration statistics.

(fn SESSION)" t)
(autoload 'detached-attach-session "detached" "\
Attach to SESSION.

(fn SESSION)" t)
(autoload 'detached-copy-session-output "detached" "\
Copy SESSION's output.

(fn SESSION)" t)
(autoload 'detached-copy-session-command "detached" "\
Copy SESSION's command.

(fn SESSION)" t)
(autoload 'detached-insert-session-command "detached" "\
Insert SESSION's command.

(fn SESSION)" t)
(autoload 'detached-delete-session "detached" "\
Delete SESSION.

(fn SESSION)" t)
(autoload 'detached-kill-session "detached" "\
Send a TERM signal to SESSION.

Optionally DELETE the session if prefix-argument is provided.

(fn SESSION &optional DELETE)" t)
(autoload 'detached-view-session "detached" "\
View the SESSION.

(fn SESSION)" t)
(autoload 'detached-diff-session "detached" "\
Diff SESSION1 with SESSION2.

(fn SESSION1 SESSION2)" t)
(autoload 'detached-open-session-directory "detached" "\
Open SESSION's log directory.

(fn SESSION)" t)
(autoload 'detached-detach-session "detached" "\
Detach from session in current buffer.

This command is only activated if `detached-buffer-session' is an
active session.  For sessions created with `detached-compile' or
`detached-shell-command', the command will also kill the window." t)
(autoload 'detached-delete-sessions "detached" "\
Delete `detached' sessions which belong to the current host, unless ALL-HOSTS.

(fn &optional ALL-HOSTS)" t)
(autoload 'detached-initialize-sessions "detached" "\
Initialize `detached' sessions from the database.")
(autoload 'detached-shell-mode "detached" "\
Integrate `detached' in `shell-mode'.

This is a minor mode.  If called interactively, toggle the
`detached-shell mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `detached-shell-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

\\{detached-shell-mode-map}

(fn &optional ARG)" t)
(autoload 'detached-log-mode "detached" "\
Major mode for `detached' logs.

(fn)" t)
(register-definition-prefixes "detached" '("detached-"))


;;; Generated autoloads from detached-compile.el

(autoload 'detached-compile "detached-compile" "\
Run COMMAND through `compile' but in a `detached' session.
Optionally enable COMINT if prefix-argument is provided.

(fn COMMAND &optional COMINT)" t)
(autoload 'detached-compile-recompile "detached-compile" "\
Re-compile by running `compile' but in a `detached' session.
Optionally EDIT-COMMAND.

(fn &optional EDIT-COMMAND)" t)
(autoload 'detached-compile-attach "detached-compile" "\
Attach to SESSION with `compile'.

(fn SESSION)")
(autoload 'detached-compile-start-session "detached-compile" "\
Start SESSION with `detached-compile'.

(fn SESSION)")
(autoload 'detached-compile--start "detached-compile" "\
Run in `compilation-start-hook' if `detached-enabled'.

(fn _)")
(autoload 'detached-compilation-mode "detached-compile" "\
Major mode for `detached' compilation.

(fn)" t)
(register-definition-prefixes "detached-compile" '("detached-compil"))


;;; Generated autoloads from detached-consult.el

(autoload 'detached-consult-session "detached-consult" "\
Enhanced `detached-open-session' command." t)
(register-definition-prefixes "detached-consult" '("detached-consult-"))


;;; Generated autoloads from detached-dired.el

(autoload 'detached-dired-do-shell-command "detached-dired" "\
Ensure `detached' is used before running DIRED-DO-SHELL-COMMAND with ARGS.

(fn DIRED-DO-SHELL-COMMAND &rest ARGS)")


;;; Generated autoloads from detached-eshell.el

(autoload 'detached-eshell-external-command "detached-eshell" "\
Advice ORIG-FUN to optionally use `detached' on ARGS.

(fn ORIG-FUN &rest ARGS)")
(autoload 'detached-eshell-mode "detached-eshell" "\
Integrate `detached' in `eshell-mode'.

This is a minor mode.  If called interactively, toggle the
`detached-eshell mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `detached-eshell-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "detached-eshell" '("detached-eshell-"))


;;; Generated autoloads from detached-extra.el

(autoload 'detached-extra-projectile-run-compilation "detached-extra" "\
If CMD is a string execute it with `detached-compile'.

Optionally USE-COMINT-MODE

(fn CMD &optional USE-COMINT-MODE)")
(autoload 'detached-extra-dired-rsync "detached-extra" "\
Run COMMAND with `detached'.

(fn COMMAND DETAILS)")
(autoload 'detached-extra-alert-notification "detached-extra" "\
Send an `alert' notification when SESSION becomes inactive.

(fn SESSION)")


;;; Generated autoloads from detached-init.el

(autoload 'detached-init "detached-init" "\
Initialize `detached' integration with all packages.")
(register-definition-prefixes "detached-init" '("detached-"))


;;; Generated autoloads from detached-list.el

(autoload 'detached-list-sessions "detached-list" "\
Open list of `detached'." t)
(register-definition-prefixes "detached-list" '("detached-"))


;;; Generated autoloads from detached-org.el

(autoload 'detached-org-babel-sh "detached-org" "\
Modify ARGS before calling ORG-BABEL-SH-EVALUATE-FUN.

This function modifies the full-body in ARGS and replaces it with a
`detached' command.  The functionality is enabled by setting a header
property of :detached t in the org babel src block.

(fn ORG-BABEL-SH-EVALUATE-FUN &rest ARGS)")
(register-definition-prefixes "detached-org" '("detached-org-session-action"))


;;; Generated autoloads from detached-shell.el

(autoload 'detached-shell-override-history "detached-shell" "\
Override history in ORIG-FUN with ARGS.

This function also makes sure that the HISTFILE is disabled for local shells.

(fn ORIG-FUN &rest ARGS)")
(autoload 'detached-shell-save-history-on-kill "detached-shell" "\
Add hook to save history when killing `shell' buffer.")
(register-definition-prefixes "detached-shell" '("detached-shell-"))


;;; Generated autoloads from detached-vterm.el

(autoload 'detached-vterm-mode "detached-vterm" "\
Integrate `detached' in `vterm'.

This is a minor mode.  If called interactively, toggle the
`detached-vterm mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `detached-vterm-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "detached-vterm" '("detached-vterm-"))

;;; End of scraped data

(provide 'detached-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; detached-autoloads.el ends here
