;;; engrave-faces-autoloads.el --- automatically extracted autoloads
;;
;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))


;;;### (autoloads nil "engrave-faces" "engrave-faces.el" (0 0 0 0))
;;; Generated autoloads from engrave-faces.el

(autoload 'engrave-faces-define-backend "engrave-faces" "\
Create a new engraving backend BACKEND.
EXTENSION is the extension which will be used when writing engraved files.
FACE-TRANSFORMER is the all important function which can be called with a
list of faces and some content to apply those faces to and generate an output
string accordingly.
Should a pre/postable make sense for complete files using BACKEND, a
STANDALONE-TRANSFORMER may be defined which operates on a buffer which has been
generated by `engrave-faces-buffer' and is called after hooks.
If STANDALONE-TRANSFORMER is given it will be used when directly creating a file,
and cause a -standalone version of the buffer transforming function to be created.

\(fn BACKEND EXTENSION FACE-TRANSFORMER &optional STANDALONE-TRANSFORMER VIEW-SETUP)" nil t)

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "engrave-faces" '("engrave-faces-")))

;;;***

;;;### (autoloads nil "engrave-faces-ansi" "engrave-faces-ansi.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from engrave-faces-ansi.el
 (autoload #'engrave-faces-ansi-buffer "engrave-faces-ansi" nil t)
 (autoload #'engrave-faces-ansi-file "engrave-faces-ansi" nil t)

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "engrave-faces-ansi" '("engrave-faces-ansi-")))

;;;***

;;;### (autoloads nil "engrave-faces-html" "engrave-faces-html.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from engrave-faces-html.el
 (autoload #'engrave-faces-html-buffer "engrave-faces-html" nil t)
 (autoload #'engrave-faces-html-buffer-standalone "engrave-faces-html" nil t)
 (autoload #'engrave-faces-html-file "engrave-faces-html" nil t)

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "engrave-faces-html" '("engrave-faces-html-")))

;;;***

;;;### (autoloads nil "engrave-faces-latex" "engrave-faces-latex.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from engrave-faces-latex.el
 (autoload #'engrave-faces-latex-buffer "engrave-faces-latex" nil t)
 (autoload #'engrave-faces-latex-buffer-standalone "engrave-faces-latex" nil t)
 (autoload #'engrave-faces-latex-file "engrave-faces-latex" nil t)

(if (fboundp 'register-definition-prefixes) (register-definition-prefixes "engrave-faces-latex" '("engrave-faces-latex-")))

;;;***

;;;### (autoloads nil nil ("engrave-faces-pkg.el") (0 0 0 0))

;;;***

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8
;; End:
;;; engrave-faces-autoloads.el ends here
